# Generated by Django 4.2 on 2023-05-19 10:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("hotel", "__first__"),
    ]

    operations = [
        migrations.CreateModel(
            name="Booking",
            fields=[
                (
                    "booking_id",
                    models.AutoField(editable=False, primary_key=True, serialize=False),
                ),
                ("booking_time", models.DateTimeField(null=True)),
                ("check_out_time", models.DateTimeField(auto_now_add=True)),
                ("booking_status", models.IntegerField(default=0)),
                (
                    "hotel_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hotelid",
                        to="hotel.hotel",
                    ),
                ),
                (
                    "user_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="userid",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
